--------------------------------------------------------------------------------------------------------------------------------------
------------------------ BLIPS CONFIGURATION ------------------------------------------------ BLIPS DISPLAY SETTINGS -----------------
--------------------------------------------------------------------------------------------------------------------------------------
--- label | "blipname"                                                      ------                                                 ---
--- coords | vector3(x, y, z)                                               ------ 0 = Not Displays                                ---
--- display | 0 or 2 or 3 or 5 or 8                                         ------ 2 = Map and Minimap (Selectable on Map)         ---
--- sprite | https://docs.fivem.net/docs/game-references/blips/#blips       ------ 3 = Only Map                                    ---
--- color | https://docs.fivem.net/docs/game-references/blips/#blip-colors  ------ 5 = Only Minimap                                ---
--- alpha | 0 to 255 number (255 is opaque)                                 ------ 8 = Map and Minimap (Not selectable on Map)     ---
--- scale | 0.1 to 1.0 number                                               ------                                                 ---
--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------
return {
    Blips = {
        ["police"] = {
            label = "Centrale Polizia",
            coords = vector3(425.9381, -981.3098, 30.7098),
            display = 2,
            sprite = 60,
            color = 29,
            alpha = 255,
            scale = 0.8,
        },
        ["hospital"] = {
            label = "Ospedale",
            coords = vector3(-842.7508, -1206.5000, 6.4033),
            display = 2,
            sprite = 61,
            color = 25,
            alpha = 255,
            scale = 0.8,
        },
        ["tropical"] = {
            label = "Tropical Heights",
            coords = vector3(285.2625, -919.7712, 29.1527),
            display = 2,
            sprite = 93,
            color = 27,
            alpha = 255,
            scale = 0.8,
        },
        ["vanilla"] = {
            label = "Vanilla Unicorn",
            coords = vector3(131.8794, -1303.9832, 29.2237),
            display = 2,
            sprite = 121,
            color = 48,
            alpha = 255,
            scale = 0.8,
        },
        ["bahamas"] = {
            label = "Bahamas Mamas",
            coords = vector3(-1390.3949, -584.5335, 30.2246),
            display = 2,
            sprite = 121,
            color = 47,
            alpha = 255,
            scale = 0.8,
        },
        ["kebabking"] = {
            label = "Doner Kebab",
            coords = vector3(247.9649, -827.0901, 29.8451),
            display = 2,
            sprite = 355,
            color = 21,
            alpha = 255,
            scale = 0.8,
        },
        ["burgershot"] = {
            label = "Burger Shot",
            coords = vector3(-1180.4214, -874.8411, 13.9576),
            display = 2,
            sprite = 106,
            color = 59,
            alpha = 255,
            scale = 0.8,
        },
        ["ammunation200"] = {
            label = "Ammu-Nation 200",
            coords = vector3(16.6642, -1116.8182, 29.7912),
            display = 2,
            sprite = 110,
            color = 1,
            alpha = 255,
            scale = 0.8,
        },
        ["lsc"] = {
            label = "LS Customs",
            coords = vector3(-381.0518, -119.8198, 38.6882),
            display = 2,
            sprite = 523,
            color = 1,
            alpha = 255,
            scale = 0.8,
        },
        ["vicecardealer"] = {
            label = "Vice Car Dealer",
            coords = vector3(-291.7906, -835.6619, 31.6475),
            display = 2,
            sprite = 523,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["bennysracetrack"] = {
            label = "Bennys Racetrack",
            coords = vector3(-746.5958, -2048.8276, 8.3950),
            display = 2,
            sprite = 309,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["milehigh"] = {
            label = "Mile High Club",
            coords = vector3(-107.5170, -959.7780, 29.2805),
            display = 2,
            sprite = 475,
            color = 70,
            alpha = 255,
            scale = 0.8,
        },
        ["vangelico"] = {
            label = "Vangelico",
            coords = vector3(-446.7056, -80.3315, 40.5574),
            display = 2,
            sprite = 617,
            color = 3,
            alpha = 255,
            scale = 0.8,
        },
        ["bennysluxury"] = {
            label = "Bennys Luxury",
            coords = vector3(-913.0969, -2040.0156, 9.4054),
            display = 2,
            sprite = 225,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["dailyglobe"] = {
            label = "Daily Globe",
            coords = vector3(-281.9511, -603.3431, 33.5589),
            display = 2,
            sprite = 590,
            color = 2,
            alpha = 255,
            scale = 0.8,
        },
        ["hotwheels"] = {
            label = "Hot Wheels Custom",
            coords = vector3(-171.4111, -33.8790, 52.2772),
            display = 2,
            sprite = 488,
            color = 1,
            alpha = 255,
            scale = 0.8,
        },
        ["government"] = {
            label = "Government",
            coords = vector3(-533.7270, -223.6790, 37.6501),
            display = 2,
            sprite = 419,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["bushplanet"] = {
            label = "Bush Planet",
            coords = vector3(-1528.9736, -415.6638, 35.5926),
            display = 2,
            sprite = 140,
            color = 25,
            alpha = 255,
            scale = 0.8,
        },
        ["vespucci"] = {
            label = "Vespucci",
            coords = vector3(-1423.4109, -1238.5897, 4.4039),
            display = 2,
            sprite = 93,
            color = 25,
            alpha = 255,
            scale = 0.8,
        },
        ["asgard"] = {
            label = "Asgard",
            coords = vector3(-1735.6562, -744.0536, 10.1739),
            display = 2,
            sprite = 93,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["pacificbluffs"] = {
            label = "Pacific Bluffs",
            coords = vector3(-3002.6216, 110.2571, 14.1817),
            display = 2,
            sprite = 93,
            color = 29,
            alpha = 255,
            scale = 0.8,
        },
        ["bennysdocks"] = {
            label = "Japan Garage",
            coords = vector3(175.6095, -3034.0317, 5.7875),
            display = 2,
            sprite = 523,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["cayobridge"] = {
            label = "Cayo Bridge",
            coords = vector3(1444.9517, -2590.5020, 50.0023),
            display = 2,
            sprite = 765,
            color = 0,
            alpha = 255,
            scale = 0.8,
        },
        ["blazeit"] = {
            label = "Blaze It",
            coords = vector3(374.9080, -1268.1802, 32.5033),
            display = 2,
            sprite = 140,
            color = 25,
            alpha = 255,
            scale = 0.8,
        },
    },
}